### ISSUE TITLE
Project review

### ISSUE THREAD

**Issue by gabyse1** [danielufeli/recipe-app-rails-group-capstone#11]
## Hello Reviewer. 😃 
First all all thank you for the review.

Our team is made up of two members.

https://github.com/danielufeli/recipe-app-rails-group-capstone/projects/1

**Comment by rotimiazeez** [comment]
# Hi Team👋, 

### Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
